modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
# The modid of the mod
modId="block_clover" #mandatory
version="0.5.0" #mandatory
 # A display name for the mod
displayName="Block Clover" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks to your mother for physically supporting me through this project" #optional
authors="Beosti, Con, honorable mentions: Wynd" #optional
description='''
Black clover mod, big thanks to Jo for his original mod
Big thanks to my patrons:
Kausu, Maddox, Redwolf'''
[[dependencies.block_clover]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.block_clover]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"